package:
  name: root
  version: "6.14.04"

source:
  git_rev: v6-14-04
  git_url: "https://github.com/root-project/root.git"

build:
  detect_binary_files_with_prefix: True

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make # [linux]
    - python
    - pcre
    - xz


  host:
    - python
    - numpy
    - openssl
    - sqlite
    - pcre
    - libxml2
    - icu
    - graphviz
    - xz
    - tbb
    - zlib
    - gsl # [osx]
    - freetype # [osx]
    - krb5 # [osx]
    - libuuid # [linux]

  run:
    - python
    - numpy
    - openssl
    - sqlite
    - pcre
    - libxml2
    - icu
    - graphviz
    - xz
    - tbb
    - zlib
    - gsl # [osx]
    - freetype # [osx]
    - krb5 # [osx]
    - libuuid # [linux]

test:
  #imports:
    #- ROOT
  commands:
    - root -b -q
    - which root
    - source thisroot.sh
    - python -c "import ROOT"

about:
  home: "https://root.cern.ch"
  license: "LGPL 2.1+"
  license_file: LICENSE
